Revert import ordering in ModelRegistryTest
Fix following build error:
Building CXX object CMakeFiles/devmantest.dir/src/devmand/test/cli/ModelRegistryTest.cpp.o
In file included from /usr/include/folly/futures/Promise.h:23:0,
                 from /usr/include/folly/futures/Future.h:35,
                 from /tmp/tmp.b3ST8Q971X/src/devmand/test/cli/ModelRegistryTest.cpp:11:
/usr/include/folly/futures/detail/Core.h: In member function 'void folly::futures::detail::Core<T>::raise(folly::exception_wrapper)':
/usr/include/folly/futures/detail/Core.h:445:68: error: call of overloaded 'make_unique(std::remove_reference<folly::exception_wrapper&>::type)' is ambiguous
       interrupt_ = std::make_unique<exception_wrapper>(std::move(e));
                                                                    ^
compilation terminated due to -Wfatal-errors.